### ISSUE TITLE
updatesite latest does not reference latest release

### ISSUE THREAD

**Issue by JanWittler** [kit-sdq/SDQ-Commons#41]
The updatesite latest ref (https://github.com/kit-sdq/updatesite/blob/master/release/commons/latest) does not reference the latest version.

**Comment by JanWittler** [comment]
@larsk21 @TomWerm results in issues when using Vitruv in Eclipse for me.

**Comment by larsk21** [comment]
Do we have automation for this (CI, scripts, ...) or do we have to do this manually for each release?

**Comment by JanWittler** [comment]
I don't think we have automation for this (yet).
